services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.prod.example
    restart: always
    command: >
      sh -c "
      pnpm run db:migrate && pnpm run start"

  db:
    image: postgres:16.3
    env_file:
      - .env.prod.example
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
