services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.prod.example
    restart: always
    command: >
      sh -c "
      yarn run db:migrate && yarn run start"
